In [34]:
import pandas as pd 
data = pd.read_csv("../Data/3rd_boston_housing.csv", encoding="utf-8")
data.head()

crim    zn  indus  chas    nox     rm   age     dis  rad  tax  pratio  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296    15.3   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242    17.8   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242    17.8   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222    18.7   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222    18.7   

        b  lstat  medv  
0  396.90   4.98  24.0  
1  396.90   9.14  21.6  
2  392.83   4.03  34.7  
3  394.63   2.94  33.4  
4  396.90   5.33  36.2

- crim 항목의 상위 10번째 값으로 상위 10개의 값을 변환하고 age 80이상인 값에 대하여 crim 평균을 구하시오

In [35]:
data_crim = data['crim'].sort_values(ascending=False)

In [39]:
data_crim[:10]
# 상위 10번째 값은 25.9406

380    88.9762
418    73.5341
405    67.9208
410    51.1358
414    45.7461
404    41.5292
398    38.3518
427    37.6619
413    28.6558
417    25.9406
Name: crim, dtype: float64

In [40]:
data_sort = data.sort_values(by="crim", ascending=False)
data_sort
# crim을 기준으로 정렬 

crim    zn  indus  chas    nox     rm    age     dis  rad  tax  \
380  88.97620   0.0  18.10     0  0.671  6.968   91.9  1.4165   24  666   
418  73.53410   0.0  18.10     0  0.679  5.957  100.0  1.8026   24  666   
405  67.92080   0.0  18.10     0  0.693  5.683  100.0  1.4254   24  666   
410  51.13580   0.0  18.10     0  0.597  5.757  100.0  1.4130   24  666   
414  45.74610   0.0  18.10     0  0.693  4.519  100.0  1.6582   24  666   
..        ...   ...    ...   ...    ...    ...    ...     ...  ...  ...   
55    0.01311  90.0   1.22     0  0.403  7.249   21.9  8.6966    5  226   
341   0.01301  35.0   1.52     0  0.442  7.241   49.3  7.0379    1  284   
285   0.01096  55.0   2.25     0  0.389  6.453   31.9  7.3073    1  300   
284   0.00906  90.0   2.97     0  0.400  7.088   20.8  7.3073    1  285   
0     0.00632  18.0   2.31     0  0.538  6.575   65.2  4.0900    1  296   

     pratio       b  lstat  medv  
380    20.2  396.90  17.21  10.4  
418    20.2   16.45  20.62   8.8  
405    20.2  384.97  22.98   5.0  
410    20.2    2.60  10.11  15.0  
414    20.2   88.27  36.98   7.0  
..      ...     ...    ...   ...  
55     17.9  395.93   4.81  35.4  
341    15.5  394.74   5.49  32.7  
285    15.3  394.72   8.23  22.0  
284    15.3  394.72   7.85  32.2  
0      15.3  396.90   4.98  24.0  

[506 rows x 14 columns]

In [41]:
def sort_crim(series):
    if series >= 25.9406:
        return 25.9406
    else:
        return series;

In [42]:
data_sort['crim'].apply(sort_crim)

380    25.94060
418    25.94060
405    25.94060
410    25.94060
414    25.94060
         ...   
55      0.01311
341     0.01301
285     0.01096
284     0.00906
0       0.00632
Name: crim, Length: 506, dtype: float64

In [43]:
data_sort['newCrim'] = data_sort['crim'].apply(sort_crim)
data_sort

crim    zn  indus  chas    nox     rm    age     dis  rad  tax  \
380  88.97620   0.0  18.10     0  0.671  6.968   91.9  1.4165   24  666   
418  73.53410   0.0  18.10     0  0.679  5.957  100.0  1.8026   24  666   
405  67.92080   0.0  18.10     0  0.693  5.683  100.0  1.4254   24  666   
410  51.13580   0.0  18.10     0  0.597  5.757  100.0  1.4130   24  666   
414  45.74610   0.0  18.10     0  0.693  4.519  100.0  1.6582   24  666   
..        ...   ...    ...   ...    ...    ...    ...     ...  ...  ...   
55    0.01311  90.0   1.22     0  0.403  7.249   21.9  8.6966    5  226   
341   0.01301  35.0   1.52     0  0.442  7.241   49.3  7.0379    1  284   
285   0.01096  55.0   2.25     0  0.389  6.453   31.9  7.3073    1  300   
284   0.00906  90.0   2.97     0  0.400  7.088   20.8  7.3073    1  285   
0     0.00632  18.0   2.31     0  0.538  6.575   65.2  4.0900    1  296   

     pratio       b  lstat  medv   newCrim  
380    20.2  396.90  17.21  10.4  25.94060  
418    20.2   16.45  20.62   8.8  25.94060  
405    20.2  384.97  22.98   5.0  25.94060  
410    20.2    2.60  10.11  15.0  25.94060  
414    20.2   88.27  36.98   7.0  25.94060  
..      ...     ...    ...   ...       ...  
55     17.9  395.93   4.81  35.4   0.01311  
341    15.5  394.74   5.49  32.7   0.01301  
285    15.3  394.72   8.23  22.0   0.01096  
284    15.3  394.72   7.85  32.2   0.00906  
0      15.3  396.90   4.98  24.0   0.00632  

[506 rows x 15 columns]

In [44]:
data_sort[data_sort['age'] >= 80]['newCrim'].mean()


5.759386624999999

- 첫번째 행부터 순서대로 80%까지의 데이터를 훈련 데이터로 추출 후 total_bedrooms 변수의 결측값을 total_bedrooms 변수의 중앙값으로 대체하고 대체 전의 total_bedrooms변수의 표준편차 값의 차이의 절대값을 구하시오

In [46]:
import pandas as pd 
data = pd.read_csv("../Data/california_housing.csv", encoding="utf-8")
data.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   
1    -122.22     37.86                21.0       7099.0          1106.0   
2    -122.24     37.85                52.0       1467.0           190.0   
3    -122.25     37.85                52.0       1274.0           235.0   
4    -122.25     37.85                52.0       1627.0           280.0   

   population  households  median_income  median_house_value ocean_proximity  
0       322.0       126.0         8.3252            452600.0        NEAR BAY  
1      2401.0      1138.0         8.3014            358500.0        NEAR BAY  
2       496.0       177.0         7.2574            352100.0        NEAR BAY  
3       558.0       219.0         5.6431            341300.0        NEAR BAY  
4       565.0       259.0         3.8462            342200.0        NEAR BAY

In [49]:
print(len(data))

20640


In [50]:
20640 * 0.8

16512.0

In [52]:
data2 = data[:16512]
print(len(data2))

16512


In [53]:
data2

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -122.23     37.88                41.0        880.0           129.0   
1        -122.22     37.86                21.0       7099.0          1106.0   
2        -122.24     37.85                52.0       1467.0           190.0   
3        -122.25     37.85                52.0       1274.0           235.0   
4        -122.25     37.85                52.0       1627.0           280.0   
...          ...       ...                 ...          ...             ...   
16507    -121.11     37.74                11.0       3886.0           599.0   
16508    -121.10     37.80                35.0       1853.0           331.0   
16509    -121.11     37.76                22.0       2606.0           411.0   
16510    -121.16     37.73                 7.0       4956.0           941.0   
16511    -121.25     37.76                22.0       2430.0           417.0   

       population  households  median_income  median_house_value  \
0           322.0       126.0         8.3252            452600.0   
1          2401.0      1138.0         8.3014            358500.0   
2           496.0       177.0         7.2574            352100.0   
3           558.0       219.0         5.6431            341300.0   
4           565.0       259.0         3.8462            342200.0   
...           ...         ...            ...                 ...   
16507      1605.0       529.0         4.4213            182700.0   
16508       958.0       340.0         3.3578            149000.0   
16509      1252.0       397.0         4.1833            192100.0   
16510      3006.0       915.0         3.4426            139000.0   
16511      1292.0       391.0         3.4009            182400.0   

      ocean_proximity  
0            NEAR BAY  
1            NEAR BAY  
2            NEAR BAY  
3            NEAR BAY  
4            NEAR BAY  
...               ...  
16507          INLAND  
16508          INLAND  
16509          INLAND  
16510          INLAND  
16511          INLAND  

[16512 rows x 10 columns]

In [47]:
import numpy as np 

In [55]:
notChangeStd = np.std(data2['total_bedrooms'])
print(notChangeStd)

435.8872490013688


In [70]:
std = data2['total_bedrooms'].std()
print(std)

435.900577052527


In [65]:
print(data2['total_bedrooms'].isnull().sum())

159


In [68]:
data2['total_bedrooms'].median()

436.0

In [61]:
data2['ch_total_bedrooms'] = data2['total_bedrooms'].fillna(data2['total_bedrooms'].median())

0


/var/folders/rn/572w08lj1f91tkntfly8qw7h0000gn/T/ipykernel_12649/3376139528.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data2['ch_total_bedrooms'] = data2['total_bedrooms'].fillna(data2['total_bedrooms'].median())


In [62]:
print(data2['ch_total_bedrooms'].isnull().sum())

0


In [66]:
changeStd = np.std(data2['ch_total_bedrooms'])
print(changeStd)

433.9122898626312


In [71]:
cStd = data2['ch_total_bedrooms'].std()
print(cStd)

433.9254297608813


In [67]:
notChangeStd - changeStd

1.9749591387375744

In [72]:
abs(std-cStd)

1.975147291645726

- insurance 데이터 셋으로 charges 항목의 이상값의 합을 구하시오 

In [73]:
import pandas as pd 
data = pd.read_csv("../Data/insurance.csv", encoding="utf-8")

In [74]:
data.head()

age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [77]:
charges_std = data['charges'].std()
print(charges_std)

12110.011236693994


In [83]:
standard1 = data['charges'].mean() + charges_std * 1.5
standard2 = data['charges'].mean() - charges_std * 1.5
print(standard1)
print(standard2)

31435.439120182247
-4894.594589899734


In [84]:
sum = 0
for i in data['charges']:
    if i > standard1 or i < standard2:
        sum += i
print(sum)

6421430.020670003


- E-commerce Shipping data의 train set을 참조하여 고객이 주문한 물품의 정시 도착 여부를 예측하시오

In [1]:
import pandas as pd 
test = pd.read_csv("../Data/commerce/X_test.csv", encoding="utf-8")
X_train = pd.read_csv("../Data/commerce/X_train.csv", encoding="utf-8")
y_train = pd.read_csv("../Data/commerce/y_train.csv", encoding="utf-8")

In [3]:
X_train.head()

ID Warehouse_block Mode_of_Shipment  Customer_care_calls  Customer_rating  \
0   1               B             Ship                    3                4   
1   2               F             Ship                    4                3   
2   3               B             Ship                    2                1   
3   4               F             Ship                    6                5   
4   5               F           Flight                    3                1   

   Cost_of_the_Product  Prior_purchases Product_importance Gender  \
0                  134                3               high      F   
1                  173                3             medium      M   
2                  192                3               high      M   
3                  284                4             medium      M   
4                  246                3                low      F   

   Discount_offered  Weight_in_gms  
0                 6           5680  
1                 5           5331  
2                46           3206  
3                 8           5346  
4                10           4707

In [10]:
for i in X_train:
    print(i, "의 고유값들은 : " ,X_train[i].unique())

ID 의 고유값들은 :  [   1    2    3 ... 8797 8798 8799]
Warehouse_block 의 고유값들은 :  ['B' 'F' 'C' 'A' 'D']
Mode_of_Shipment 의 고유값들은 :  ['Ship' 'Flight' 'Road']
Customer_care_calls 의 고유값들은 :  [3 4 2 6 5 7]
Customer_rating 의 고유값들은 :  [4 3 1 5 2]
Cost_of_the_Product 의 고유값들은 :  [134 173 192 284 246 211 238 178 198 214 234 146 194 241 260 162 205 240
 275 151 181 140 152 157 167 248 249 203 201 243 287 256 190 141 145 135
 164 227 274 286 144 222 158 161 250 245 125 252 189 269 231 233 191 257
 268 217 163 225 172 133 263 150 199 143 220 216 116 175 208 267 228 242
 213 149 202 255 166 244 277 223 295 180 302 171 254 253 276 184 219 307
 264 305 271 170 258 159 236 204 265 174 239 187 188 259 272 197 210 229
 261 266 221 195 142 212 296 137 182 148 209 237 176 185 139 156 154 155
 153 224 132 262 281 270 136 169 104 111 102 207 301 165 283 160 183 226
 127 285 291 273 280 292 251 179 230 108 279 118 218  98 177 129 138 289
 293 247 200 306 186 193 232 235 278 308 123 110 168 215 196 310 282 128
 12

In [11]:
# category : Warehouse_block, Mode_of_Shipment, Product_importance, Gender
# 나머지 : Customer_care_calls, Customer_rating, Cost_of_the_Product, Prior_purchases, Discount_offered, Weight_in_gms

X_category = X_train[['Warehouse_block', 'Mode_of_Shipment', 'Product_importance', 'Gender']]
X_category

Warehouse_block Mode_of_Shipment Product_importance Gender
0                  B             Ship               high      F
1                  F             Ship             medium      M
2                  B             Ship               high      M
3                  F             Ship             medium      M
4                  F           Flight                low      F
...              ...              ...                ...    ...
8794               C             Ship                low      F
8795               F             Ship             medium      F
8796               D             Ship             medium      M
8797               B             Ship             medium      F
8798               A           Flight                low      F

[8799 rows x 4 columns]

In [13]:
X_number = X_train[['Customer_care_calls', 'Customer_rating', 'Cost_of_the_Product', 'Prior_purchases', 'Discount_offered', 'Weight_in_gms']]
X_number

Customer_care_calls  Customer_rating  Cost_of_the_Product  \
0                       3                4                  134   
1                       4                3                  173   
2                       2                1                  192   
3                       6                5                  284   
4                       3                1                  246   
...                   ...              ...                  ...   
8794                    6                5                  178   
8795                    3                1                  206   
8796                    4                1                  135   
8797                    4                4                  251   
8798                    6                4                  144   

      Prior_purchases  Discount_offered  Weight_in_gms  
0                   3                 6           5680  
1                   3                 5           5331  
2                   3                46           3206  
3                   4                 8           5346  
4                   3                10           4707  
...               ...               ...            ...  
8794                3                 5           4096  
8795                2                56           2069  
8796               10                35           1989  
8797                2                 6           4376  
8798                4                 5           4631  

[8799 rows x 6 columns]

In [14]:
X_category_dum = pd.get_dummies(X_category)
X_category_dum

Warehouse_block_A  Warehouse_block_B  Warehouse_block_C  \
0                     0                  1                  0   
1                     0                  0                  0   
2                     0                  1                  0   
3                     0                  0                  0   
4                     0                  0                  0   
...                 ...                ...                ...   
8794                  0                  0                  1   
8795                  0                  0                  0   
8796                  0                  0                  0   
8797                  0                  1                  0   
8798                  1                  0                  0   

      Warehouse_block_D  Warehouse_block_F  Mode_of_Shipment_Flight  \
0                     0                  0                        0   
1                     0                  1                        0   
2                     0                  0                        0   
3                     0                  1                        0   
4                     0                  1                        1   
...                 ...                ...                      ...   
8794                  0                  0                        0   
8795                  0                  1                        0   
8796                  1                  0                        0   
8797                  0                  0                        0   
8798                  0                  0                        1   

      Mode_of_Shipment_Road  Mode_of_Shipment_Ship  Product_importance_high  \
0                         0                      1                        1   
1                         0                      1                        0   
2                         0                      1                        1   
3                         0                      1                        0   
4                         0                      0                        0   
...                     ...                    ...                      ...   
8794                      0                      1                        0   
8795                      0                      1                        0   
8796                      0                      1                        0   
8797                      0                      1                        0   
8798                      0                      0                        0   

      Product_importance_low  Product_importance_medium  Gender_F  Gender_M  
0                          0                          0         1         0  
1                          0                          1         0         1  
2                          0                          0         0         1  
3                          0                          1         0         1  
4                          1                          0         1         0  
...                      ...                        ...       ...       ...  
8794                       1                          0         1         0  
8795                       0                          1         1         0  
8796                       0                          1         0         1  
8797                       0                          1         1         0  
8798                       1                          0         1         0  

[8799 rows x 13 columns]

In [16]:
test_category = test[['Warehouse_block', 'Mode_of_Shipment', 'Product_importance', 'Gender']]
test_category

Warehouse_block Mode_of_Shipment Product_importance Gender
0                  C             Ship             medium      M
1                  F             Road             medium      M
2                  F             Ship                low      F
3                  A             Ship                low      F
4                  F             Ship                low      M
...              ...              ...                ...    ...
2195               F             Ship                low      M
2196               F             Ship             medium      F
2197               B             Ship             medium      F
2198               D             Ship                low      F
2199               B             Ship             medium      F

[2200 rows x 4 columns]

In [17]:
test_number = test[['Customer_care_calls', 'Customer_rating', 'Cost_of_the_Product', 'Prior_purchases', 'Discount_offered', 'Weight_in_gms']]
test_number

Customer_care_calls  Customer_rating  Cost_of_the_Product  \
0                       5                5                  250   
1                       5                2                  202   
2                       5                4                  154   
3                       6                4                  209   
4                       6                1                  250   
...                   ...              ...                  ...   
2195                    4                3                  131   
2196                    2                1                  166   
2197                    3                5                  202   
2198                    3                5                  224   
2199                    3                2                  224   

      Prior_purchases  Discount_offered  Weight_in_gms  
0                   2                10           5475  
1                   3                34           3885  
2                   2                 5           5528  
3                   5                53           3169  
4                   4                 4           1018  
...               ...               ...            ...  
2195                5                 6           1659  
2196                3                 7           5990  
2197                2                 8           4552  
2198                2                10           4445  
2199                2                 3           4405  

[2200 rows x 6 columns]

In [18]:
test_category_dum = pd.get_dummies(test_category)
test_category_dum

Warehouse_block_A  Warehouse_block_B  Warehouse_block_C  \
0                     0                  0                  1   
1                     0                  0                  0   
2                     0                  0                  0   
3                     1                  0                  0   
4                     0                  0                  0   
...                 ...                ...                ...   
2195                  0                  0                  0   
2196                  0                  0                  0   
2197                  0                  1                  0   
2198                  0                  0                  0   
2199                  0                  1                  0   

      Warehouse_block_D  Warehouse_block_F  Mode_of_Shipment_Flight  \
0                     0                  0                        0   
1                     0                  1                        0   
2                     0                  1                        0   
3                     0                  0                        0   
4                     0                  1                        0   
...                 ...                ...                      ...   
2195                  0                  1                        0   
2196                  0                  1                        0   
2197                  0                  0                        0   
2198                  1                  0                        0   
2199                  0                  0                        0   

      Mode_of_Shipment_Road  Mode_of_Shipment_Ship  Product_importance_high  \
0                         0                      1                        0   
1                         1                      0                        0   
2                         0                      1                        0   
3                         0                      1                        0   
4                         0                      1                        0   
...                     ...                    ...                      ...   
2195                      0                      1                        0   
2196                      0                      1                        0   
2197                      0                      1                        0   
2198                      0                      1                        0   
2199                      0                      1                        0   

      Product_importance_low  Product_importance_medium  Gender_F  Gender_M  
0                          0                          1         0         1  
1                          0                          1         0         1  
2                          1                          0         1         0  
3                          1                          0         1         0  
4                          1                          0         0         1  
...                      ...                        ...       ...       ...  
2195                       1                          0         0         1  
2196                       0                          1         1         0  
2197                       0                          1         1         0  
2198                       1                          0         1         0  
2199                       0                          1         1         0  

[2200 rows x 13 columns]

In [19]:
# 이거는 몰랐던 거 
X_category_dum, test_category_dum = X_category_dum.align(test_category_dum, join='inner', axis = 1)


In [20]:
from sklearn.preprocessing import * 

minmax = MinMaxScaler()
minmax.fit(X_number)
X_train_scaled = minmax.transform(X_number)
X_test_scaled = minmax.transform(test_number)

print(X_train_scaled)

[[0.2        0.75       0.17757009 0.125      0.078125   0.68356465]
 [0.4        0.5        0.35981308 0.125      0.0625     0.63257852]
 [0.         0.         0.44859813 0.125      0.703125   0.32213294]
 ...
 [0.4        0.         0.18224299 1.         0.53125    0.14433893]
 [0.4        0.75       0.72429907 0.         0.078125   0.49306063]
 [0.8        0.75       0.22429907 0.25       0.0625     0.5303141 ]]


In [21]:
print(X_test_scaled)

[[0.6        1.         0.71962617 0.         0.140625   0.65361578]
 [0.6        0.25       0.4953271  0.125      0.515625   0.42132944]
 [0.6        0.75       0.27102804 0.         0.0625     0.66135866]
 ...
 [0.2        1.         0.4953271  0.         0.109375   0.51877283]
 [0.2        1.         0.59813084 0.         0.140625   0.50314098]
 [0.2        0.25       0.59813084 0.         0.03125    0.4972973 ]]


In [22]:
X_train_final = pd.concat([pd.DataFrame(X_train_scaled), X_category_dum], axis = 1)
# 데이터 합쳐줌 
X_test_final = pd.concat([pd.DataFrame(X_test_scaled), test_category_dum], axis = 1)

In [23]:
X_train_final

0     1         2      3         4         5  Warehouse_block_A  \
0     0.2  0.75  0.177570  0.125  0.078125  0.683565                  0   
1     0.4  0.50  0.359813  0.125  0.062500  0.632579                  0   
2     0.0  0.00  0.448598  0.125  0.703125  0.322133                  0   
3     0.8  1.00  0.878505  0.250  0.109375  0.634770                  0   
4     0.2  0.00  0.700935  0.125  0.140625  0.541417                  0   
...   ...   ...       ...    ...       ...       ...                ...   
8794  0.8  1.00  0.383178  0.125  0.062500  0.452155                  0   
8795  0.2  0.00  0.514019  0.000  0.859375  0.156026                  0   
8796  0.4  0.00  0.182243  1.000  0.531250  0.144339                  0   
8797  0.4  0.75  0.724299  0.000  0.078125  0.493061                  0   
8798  0.8  0.75  0.224299  0.250  0.062500  0.530314                  1   

      Warehouse_block_B  Warehouse_block_C  Warehouse_block_D  \
0                     1                  0                  0   
1                     0                  0                  0   
2                     1                  0                  0   
3                     0                  0                  0   
4                     0                  0                  0   
...                 ...                ...                ...   
8794                  0                  1                  0   
8795                  0                  0                  0   
8796                  0                  0                  1   
8797                  1                  0                  0   
8798                  0                  0                  0   

      Warehouse_block_F  Mode_of_Shipment_Flight  Mode_of_Shipment_Road  \
0                     0                        0                      0   
1                     1                        0                      0   
2                     0                        0                      0   
3                     1                        0                      0   
4                     1                        1                      0   
...                 ...                      ...                    ...   
8794                  0                        0                      0   
8795                  1                        0                      0   
8796                  0                        0                      0   
8797                  0                        0                      0   
8798                  0                        1                      0   

      Mode_of_Shipment_Ship  Product_importance_high  Product_importance_low  \
0                         1                        1                       0   
1                         1                        0                       0   
2                         1                        1                       0   
3                         1                        0                       0   
4                         0                        0                       1   
...                     ...                      ...                     ...   
8794                      1                        0                       1   
8795                      1                        0                       0   
8796                      1                        0                       0   
8797                      1                        0                       0   
8798                      0                        0                       1   

      Product_importance_medium  Gender_F  Gender_M  
0                             0         1         0  
1                             1         0         1  
2                             0         0         1  
3                             1         0         1  
4                             0         1         0  
...                         ...       ...       ...  
8794                          0         1         0  
8795                          1 

In [25]:
y_train = y_train[['Reached.on.Time_Y.N']]
y_train

Reached.on.Time_Y.N
0                       0
1                       1
2                       1
3                       1
4                       1
...                   ...
8794                    0
8795                    1
8796                    1
8797                    0
8798                    0

[8799 rows x 1 columns]

In [26]:
from sklearn.linear_model import * 
model = LogisticRegression()

model.fit(X_train_final, y_train)

/Users/sig6774/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/validation.py:1688: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  warnings.warn(
/Users/sig6774/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression()

In [27]:
model.score(X_train_final, y_train)

/Users/sig6774/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/validation.py:1688: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  warnings.warn(


0.6401863848164564

In [28]:
pred_test = model.predict_proba(X_test_final)
pred_test

/Users/sig6774/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/validation.py:1688: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['int', 'str']. An error will be raised in 1.2.
  warnings.warn(


array([[0.47662749, 0.52337251],
       [0.05438437, 0.94561563],
       [0.58713184, 0.41286816],
       ...,
       [0.40948026, 0.59051974],
       [0.37874973, 0.62125027],
       [0.55593102, 0.44406898]])

In [29]:
pred_test_prob = pd.DataFrame(pred_test[:,0], columns=['predict_prob'])
pred_test_prob

predict_prob
0         0.476627
1         0.054384
2         0.587132
3         0.010297
4         0.456478
...            ...
2195      0.343253
2196      0.523670
2197      0.409480
2198      0.378750
2199      0.555931

[2200 rows x 1 columns]

In [30]:
final_predict = pd.concat([test['ID'], pred_test_prob], axis = 1)

In [31]:
final_predict

ID  predict_prob
0      8800      0.476627
1      8801      0.054384
2      8802      0.587132
3      8803      0.010297
4      8804      0.456478
...     ...           ...
2195  10995      0.343253
2196  10996      0.523670
2197  10997      0.409480
2198  10998      0.378750
2199  10999      0.555931

[2200 rows x 2 columns]