# Numpy

In [2]:
import numpy as np

In [6]:
# numpy 배열 생성
v1 = np.array([1,2,3,4])
print(v1)

# 연속되거나 일정한 규칙을 가진 배열 생성
v1 = np.arange(5)
# 0~4까지 값  출력 
print(v1)

v2 = np.arange(1, 10, 2, dtype= int)
print(v2)
# 간격을 가질 수 있게 만들 수 있음

v3 = np.arange(1, 10, 2) **2
print(v3)
# 간격에 제곱을 취해서 배열을 만들 수 있음

[1 2 3 4]
[0 1 2 3 4]
[1 3 5 7 9]
[ 1  9 25 49 81]


In [13]:
# 행렬 만들기 
v1 = np.arange(12)
print(v1)

v2 = v1.reshape(2,6)
# 2행 6열의 행렬 생성
print(v2)

# 행렬 계산 
v1 = np.arange(4).reshape(2,2)

print(np.add(v1, v1)) # 덧셈
print(np.subtract(v1, v1)) # 뺄셈 
print(np.multiply(v1, v1)) # 곱셈 
print(np.dot(v1,v1)) # 행렬연산

# 다차원 행렬 
v1 = np.arange(12).reshape(2,3,2)
print("다차원 행렬 : \n" , v1)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[[0 2]
 [4 6]]
[[0 0]
 [0 0]]
[[0 1]
 [4 9]]
[[ 2  3]
 [ 6 11]]
다차원 행렬 : 
 [[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]


# Pandas

In [3]:
import pandas as pd 
from pandas import Series, DataFrame

In [7]:
# series : index와 value의 형태를 가지고 있는 pandas의 자료 구조 
a = Series([1, 3, 5, 7])
print(a)
print("series의 값 : " ,a.values)
print("series의 인덱스 값 : ", a.index)

a2 = pd.Series([1, 3, 5, 7], index = ['a', 'b', 'c', 'd'])
# 판다스의 인덱스 변경
print(a2)

0    1
1    3
2    5
3    7
dtype: int64
series의 값 :  [1 3 5 7]
series의 인덱스 값 :  RangeIndex(start=0, stop=4, step=1)
a    1
b    3
c    5
d    7
dtype: int64


In [17]:
# 데이터 불러오기 (csv)
df_csv = pd.read_csv('EX_GrapeData.csv' ,encoding='euc-kr')
df_csv

continent  brand  size  period price
0           2      2  10.7   47.65   144
1           2      3  14.0   63.13   215
2           2      2   9.0   58.76   105
3           1      1   8.0   34.88    69
4           2      2  10.0   55.53   134
..        ...    ...   ...     ...   ...
58          1      1   5.0   16.66  21.5
59          2      1  21.0   43.00      
60          2      2   5.0   12.00      
61          2      3  13.0   20.00      
62          2      3  31.0   19.00      

[63 rows x 5 columns]

In [19]:
# 데이터 불러오기 (xlsx)
df_excel = pd.read_excel('EX_GrapeData.xlsx')
# read_excel()함수는 더이상 encoding keword를 지원하지 않네
df_excel

continent  brand  size  period  price
0         2.0    2.0  10.7   47.65  144.0
1         2.0    3.0  14.0   63.13  215.0
2         2.0    2.0   9.0   58.76  105.0
3         1.0    1.0   8.0   34.88   69.0
4         2.0    2.0  10.0   55.53  134.0
..        ...    ...   ...     ...    ...
58        1.0    1.0   5.0   16.66   21.5
59        2.0    1.0  21.0   43.00    NaN
60        2.0    2.0   5.0   12.00    NaN
61        2.0    3.0  13.0   20.00    NaN
62        2.0    3.0  31.0   19.00    NaN

[63 rows x 5 columns]

In [25]:
# DataFrame 확인 
print(df_csv.head())

print(df_csv.tail())
# head와 tail은 공백 시 5개 행의 데이터만 불러옴

print(df_csv[0:5])
print(df_csv[:3])
print(df_csv[60:])

   continent  brand  size  period price
0          2      2  10.7   47.65   144
1          2      3  14.0   63.13   215
2          2      2   9.0   58.76   105
3          1      1   8.0   34.88    69
4          2      2  10.0   55.53   134
    continent  brand  size  period price
58          1      1   5.0   16.66  21.5
59          2      1  21.0   43.00      
60          2      2   5.0   12.00      
61          2      3  13.0   20.00      
62          2      3  31.0   19.00      
   continent  brand  size  period price
0          2      2  10.7   47.65   144
1          2      3  14.0   63.13   215
2          2      2   9.0   58.76   105
3          1      1   8.0   34.88    69
4          2      2  10.0   55.53   134
   continent  brand  size  period price
0          2      2  10.7   47.65   144
1          2      3  14.0   63.13   215
2          2      2   9.0   58.76   105
    continent  brand  size  period price
60          2      2   5.0    12.0      
61          2      3  13.0    20

In [27]:
# 데이터 불러오기 
print(df_csv['price'])
# price열의 값만 가져오기 
print(df_csv.price)

0      144
1      215
2      105
3       69
4      134
      ... 
58    21.5
59        
60        
61        
62        
Name: price, Length: 63, dtype: object
0      144
1      215
2      105
3       69
4      134
      ... 
58    21.5
59        
60        
61        
62        
Name: price, Length: 63, dtype: object


In [28]:
# 가져온 값 데이터 프레임으로 만들기 
df_csv[['price']]

price
0    144
1    215
2    105
3     69
4    134
..   ...
58  21.5
59      
60      
61      
62      

[63 rows x 1 columns]

In [31]:
# 0, 2, 4번째 컬럼만 출력 

df_csv[df_csv.columns[[0, 2, 4]]]
# 데이터 프레임.columns[[]]를 통해서 컬럼을 인덱스로 불러올 수 있음 <- 중요 

continent  size price
0           2  10.7   144
1           2  14.0   215
2           2   9.0   105
3           1   8.0    69
4           2  10.0   134
..        ...   ...   ...
58          1   5.0  21.5
59          2  21.0      
60          2   5.0      
61          2  13.0      
62          2  31.0      

[63 rows x 3 columns]

In [33]:
df_csv.loc[:, 'size' : 'price']
# loc를 통해서 size~price까지의 컬럼을 불러올 수 있음

size  period price
0   10.7   47.65   144
1   14.0   63.13   215
2    9.0   58.76   105
3    8.0   34.88    69
4   10.0   55.53   134
..   ...     ...   ...
58   5.0   16.66  21.5
59  21.0   43.00      
60   5.0   12.00      
61  13.0   20.00      
62  31.0   19.00      

[63 rows x 3 columns]

In [35]:
df_csv.iloc[1:7, 2:4]
# 1~6행까지 그리고 2,3번째 열에 속한 값 출력 

size  period
1  14.0   63.13
2   9.0   58.76
3   8.0   34.88
4  10.0   55.53
5  10.5   43.14
6  16.0   54.86

# 데이터 변환 

In [38]:
# 데이터 프레임 행 복사 
df_copy = df_csv.copy()
print(df_copy)

    continent  brand  size  period price
0           2      2  10.7   47.65   144
1           2      3  14.0   63.13   215
2           2      2   9.0   58.76   105
3           1      1   8.0   34.88    69
4           2      2  10.0   55.53   134
..        ...    ...   ...     ...   ...
58          1      1   5.0   16.66  21.5
59          2      1  21.0   43.00      
60          2      2   5.0   12.00      
61          2      3  13.0   20.00      
62          2      3  31.0   19.00      

[63 rows x 5 columns]


In [39]:
# 데이터 프레임의 컬럼 이름 확인 
df_csv.columns

Index(['continent', 'brand', 'size', 'period', 'price'], dtype='object')

In [40]:
# 데이터 컬럼 이름 수정 
print('변경 전 컬럼이름 : ', df_csv.columns)
df_csv.rename(columns ={'period' : 'time'}, inplace = True)
print('변경 후 컬럼이름 : ',df_csv.columns)
# columns를 통해 컬럼이름이 period에서 time으로 변경됨 

변경 전 컬럼이름 :  Index(['continent', 'brand', 'size', 'period', 'price'], dtype='object')
변경 후 컬럼이름 :  Index(['continent', 'brand', 'size', 'time', 'price'], dtype='object')


In [44]:
# 데이터 프레임에 있는 컬럼들을 계산해서 새로운 변수 생성
df_csv['growth'] = df_csv['size'] / df_csv['time']
print(df_csv.head())


   continent  brand  size   time price    growth
0          2      2  10.7  47.65   144  0.224554
1          2      3  14.0  63.13   215  0.221765
2          2      2   9.0  58.76   105  0.153165
3          1      1   8.0  34.88    69  0.229358
4          2      2  10.0  55.53   134  0.180083


In [45]:
# 특정 컬럼 삭제 
del df_csv['growth']
print(df_csv.head())

   continent  brand  size   time price
0          2      2  10.7  47.65   144
1          2      3  14.0  63.13   215
2          2      2   9.0  58.76   105
3          1      1   8.0  34.88    69
4          2      2  10.0  55.53   134


In [46]:
# 데이터 케이스 추출 
df_brand = df_csv[(df_csv['continent'] == 1) & (df_csv['brand'] == 1)]
# continent열의 값이 1인 것과 brand 열의 값이 1인 데이터만 추출 
print(df_brand.head())

    continent  brand  size   time price
3           1      1   8.0  34.88    69
11          1      1  10.4  17.67    54
12          1      1   7.4  16.41    39
13          1      1   5.4  12.02  29.5
16          1      1   6.0  23.21    42


In [47]:
# 데이터 케이스 추출 
df_over_size = df_csv[(df_csv['size'] >= 10) & (df_csv['time'] >= 30)]
# size열의 값이 10이상인 것과 time열의 값이 30 이상인 값 모두 추출 
print(df_over_size.head())

   continent  brand  size   time price
0          2      2  10.7  47.65   144
1          2      3  14.0  63.13   215
4          2      2  10.0  55.53   134
5          2      2  10.5  43.14   129
6          2      2  16.0  54.86   155


In [48]:
# 데이터 값 변경 
# brand 열에는 1, 2, 3이 있는데 이것을 1과 2는 1, 3은 2로 변경 

df_csv['brand'].value_counts()

2    24
1    23
3    16
Name: brand, dtype: int64

In [53]:
# 방법 1
recode_brand = {'brand' : {1: 1, 2: 1, 3: 2}}
df_recode = df_csv.replace(recode_brand)
# 지정한조건을 데이터 프레임에 적용 
print(df_recode.head())
print("===========================")
print(df_recode["brand"].value_counts())

   continent  brand  size   time price
0          2      1  10.7  47.65   144
1          2      2  14.0  63.13   215
2          2      1   9.0  58.76   105
3          1      1   8.0  34.88    69
4          2      1  10.0  55.53   134
1    47
2    16
Name: brand, dtype: int64


In [55]:
# 방법 2 함수 생성
def brand_group(series):
    if series == 1:
        return 1
    elif series == 2:
        return 1
    else:
        return 2

df_csv['re_brand'] = df_csv['brand'].apply(brand_group)
print(df_csv.head())
print("===========================")
print(df_csv["re_brand"].value_counts())

   continent  brand  size   time price  re_brand
0          2      2  10.7  47.65   144         1
1          2      3  14.0  63.13   215         2
2          2      2   9.0  58.76   105         1
3          1      1   8.0  34.88    69         1
4          2      2  10.0  55.53   134         1
1    47
2    16
Name: re_brand, dtype: int64
